name: build
on:
  pull_request:
jobs:
  linux:
    name: Linux - Build, test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update system repositories
        run: |
          sudo apt-get update
      - name: Install system dependencies
        run: |
          sudo apt install libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - name: Install LinuxDeploy
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: gstreamer appimage
          dir: /usr/local/bin
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Install dependencies
        run: |
          pnpm install
      - name: Test frontend
        run: |
          pnpm test
      - name: Lint frontend
        run: |
          pnpm lint
      - name: Test backend
        working-directory: ./src-tauri
        run: |
          cargo test
      - name: Lint backend
        working-directory: ./src-tauri
        run: |
          cargo clippy -- -D warnings
      - name: Format backend
        working-directory: ./src-tauri
        run: |
          cargo fmt -- --check
      - name: Build project
        run: |
          pnpm tauri build
  macos:
    name: MacOS - Build, test and lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Test frontend
        run: |
          pnpm test
      - name: Lint frontend
        run: |
          pnpm lint
      - name: Build project
        run: |
          pnpm tauri build
      - name: Test backend
        working-directory: ./src-tauri
        run: |
          cargo test
      - name: Lint backend
        working-directory: ./src-tauri
        run: |
          cargo clippy -- -D warnings
      - name: Format backend
        working-directory: ./src-tauri
        run: |
          cargo fmt -- --check
  windows:
    name: Windows - Build, test and lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Test frontend
        run: |
          pnpm test
      - name: Lint frontend
        run: |
          pnpm lint
      - name: Install WebView2
        run: |
          Remove-Item -Path WebView2Installer.exe -ErrorAction Ignore
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile "WebView2Installer.exe"
          if (Test-Path "WebView2Installer.exe") {
            Start-Process -FilePath WebView2Installer.exe -ArgumentList "/silent /install" -NoNewWindow -Wait
          } else {
            echo "Failed to download WebView2 installer"
            exit 1
          }
      - name: Test backend
        working-directory: ./src-tauri
        run: |
          cargo test
      - name: Lint backend
        working-directory: ./src-tauri
        run: |
          cargo clippy -- -D warnings
      - name: Format backend
        working-directory: ./src-tauri
        run: |
          cargo fmt -- --check
      - name: Build project
        run: |
          pnpm tauri build
