name: build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-lint:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        rust:
          - stable
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-latest'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Update system repositories
        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
        run: |
          sudo apt-get update

      - name: Install system dependencies
        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
        run: |
          sudo apt-get install libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install LinuxDeploy
        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: gstreamer appimage
          dir: /usr/local/bin

      - name: Install WebView2
        if: matrix.platform == 'windows-latest' # This must match the platform value defined above.
        run: |
          Remove-Item -Path WebView2Installer.exe -ErrorAction Ignore
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile "WebView2Installer.exe"
          if (Test-Path "WebView2Installer.exe") {
            Start-Process -FilePath WebView2Installer.exe -ArgumentList "/silent /install" -NoNewWindow -Wait
          } else {
            echo "Failed to download WebView2 installer"
            exit 1
          }

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ (matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin') || (matrix.platform == 'windows-latest' && 'x86_64-pc-windows-msvc') || '' }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.platform }}
          key: v1 # increment this to bust the cache if needed

      - name: Install frontend dependencies
        run: pnpm install

      - name: Format backend
        working-directory: ./src-tauri
        run: |
          cargo fmt -- --check

      - name: Build project
        run: |
          pnpm tauri build

      - name: Lint backend
        working-directory: ./src-tauri
        run: |
          cargo clippy -- -D warnings

      - name: Lint frontend
        run: |
          pnpm lint

  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        rust:
          - stable
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-latest'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Update system repositories
        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
        run: |
          sudo apt-get update

      - name: Install system dependencies
        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
        run: |
          sudo apt-get install libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install LinuxDeploy
        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: gstreamer appimage
          dir: /usr/local/bin

      - name: Install WebView2
        if: matrix.platform == 'windows-latest' # This must match the platform value defined above.
        run: |
          Remove-Item -Path WebView2Installer.exe -ErrorAction Ignore
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile "WebView2Installer.exe"
          if (Test-Path "WebView2Installer.exe") {
            Start-Process -FilePath WebView2Installer.exe -ArgumentList "/silent /install" -NoNewWindow -Wait
          } else {
            echo "Failed to download WebView2 installer"
            exit 1
          }

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ (matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin') || (matrix.platform == 'windows-latest' && 'x86_64-pc-windows-msvc') || '' }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.platform }}
          key: v1 # increment this to bust the cache if needed

      - name: Install frontend dependencies
        run: pnpm install

      - name: Test frontend
        run: |
          pnpm test

      - name: Test backend
        working-directory: ./src-tauri
        run: |
          cargo test --tests
