name: publish
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  capture-release-notes:
    runs-on: ubuntu-22.04
    outputs:
      RELEASE_NOTES: ${{ steps.set-output.outputs.RELEASE_NOTES }}
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: install frontend dependencies
        run: pnpm install

      - name: capture release notes
        run: |
          RELEASE_NOTES=$(pnpm semantic-release --dry-run --branches | sed -n '/^##/,$p')
          echo "RELEASE_NOTES=${RELEASE_NOTES}" >> $GITHUB_ENV

      - name: set step output
        id: set-output
        run: |
          echo "RELEASE_NOTES=${RELEASE_NOTES}" >> $GITHUB_OUTPUT

  publish-app:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-latest' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}

    env:
      PKG_CONFIG_PATH: "${{ matrix.platform == 'ubuntu-latest' && '/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/share' || ''}}"

    needs: capture-release-notes

    steps:
      - uses: actions/checkout@v4

      - name: Update system repositories
        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
        run: |
          sudo apt-get update

      - name: Install system dependencies
        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
        run: |
          sudo apt-get install libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install LinuxDeploy
        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: gstreamer appimage
          dir: /usr/local/bin

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ (matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin') || (matrix.platform == 'windows-latest' && 'x86_64-pc-windows-msvc') || '' }}

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: donkidunk-v__VERSION__
          releaseName: 'Donkidunk v__VERSION__'
          releaseBody: ${{ needs.capture-release-notes.outputs.RELEASE_NOTES }}
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
